/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package double_a;

import java.sql.*;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author domin
 */
public class Manager extends javax.swing.JFrame {

    public static final String username="root";
    public static final String password="97009307";
    public static final String CONN ="jdbc:mysql://localhost:3306/double_a";
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employees = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        agcode = new javax.swing.JTextField();
        jButtonRecordCheckAmountCollected = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        agentAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gincome = new javax.swing.JTextField();
        jButtonRecordComputeProfits = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        netProfit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Texpense = new javax.swing.JTextField();
        exit = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemTenantsCollection = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemMonitorDatabase = new javax.swing.JMenuItem();
        jMenuItemRegister = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Close");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 102));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pane.setBackground(new java.awt.Color(0, 0, 255));

        employees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "fname", "sname", "Id Number", "Phone Number", "Property Incharge", "Work Id Number", "Rank"
            }
        ));
        employees.setDragEnabled(true);
        employees.setEnabled(false);
        jScrollPane1.setViewportView(employees);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Enter Agent Code");

        agcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcodeActionPerformed(evt);
            }
        });

        jButtonRecordCheckAmountCollected.setBackground(new java.awt.Color(204, 0, 204));
        jButtonRecordCheckAmountCollected.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRecordCheckAmountCollected.setText("Check Amount Collected");
        jButtonRecordCheckAmountCollected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordCheckAmountCollectedActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Amount Collected");

        agentAmount.setEditable(false);
        agentAmount.setText("0.0");
        agentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentAmountActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Gross Income");

        gincome.setEditable(false);
        gincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gincomeActionPerformed(evt);
            }
        });

        jButtonRecordComputeProfits.setBackground(new java.awt.Color(204, 0, 204));
        jButtonRecordComputeProfits.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRecordComputeProfits.setText("Compute Profits");
        jButtonRecordComputeProfits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordComputeProfitsActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Profits");

        netProfit.setEditable(false);
        netProfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netProfitActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Total Expense");

        Texpense.setEditable(false);
        Texpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexpenseActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(agcode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(netProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Texpense, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(agentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gincome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButtonRecordCheckAmountCollected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                        .addComponent(jButtonRecordComputeProfits)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agcode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texpense, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gincome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneLayout.createSequentialGroup()
                        .addComponent(jButtonRecordCheckAmountCollected)
                        .addContainerGap())
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonRecordComputeProfits)
                        .addGap(83, 83, 83)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jMenu1.setText("Manager Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemTenantsCollection.setText("Check Amount Collected by all Agents");
        jMenuItemTenantsCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTenantsCollectionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTenantsCollection);

        jMenuItem3.setText("Check Profits");
        jMenu1.add(jMenuItem3);

        jMenuItemMonitorDatabase.setText("Moniter Workers");
        jMenuItemMonitorDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMonitorDatabaseActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMonitorDatabase);

        jMenuItemRegister.setText("Register new Worker or Landlord");
        jMenuItemRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegisterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRegister);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Log_In().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        Icon a= new ImageIcon("‪‪C:\\Users\\domin\\Documents\\100.jpg");
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegisterActionPerformed
        new Manager().setVisible(false); 
        new Register_Worker().setVisible(true);
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRegisterActionPerformed

    private void jMenuItemMonitorDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMonitorDatabaseActionPerformed
        try{
            con=DriverManager.getConnection(CONN, username,password);
            PreparedStatement pst=con.prepareStatement("SELECT * FROM employees");
            rs=pst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)employees.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[]={rs.getString("fname"),rs.getString("sname"),rs.getInt("id_number"),rs.getInt("phone_number"),
                            rs.getString("property_incharge"),rs.getString("w_id_number"),rs.getString("rank")};
                tm.addRow(o);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jMenuItemMonitorDatabaseActionPerformed

    private void jMenuItemTenantsCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTenantsCollectionActionPerformed
        try{
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/double_a","root","97009307");
            pst=con.prepareStatement("SELECT SUM(amount) FROM rentStatement WHERE ag_code=?");
            pst.setString(1,agcode.getText());
            rs=pst.executeQuery();
            rs.next(); 
                
                agentAmount.setText(rs.getString(1));
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jMenuItemTenantsCollectionActionPerformed

    private void TexpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexpenseActionPerformed

    private void netProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netProfitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netProfitActionPerformed

    private void jButtonRecordComputeProfitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordComputeProfitsActionPerformed
        double income, expenses;
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/double_a","root","97009307");
            pst=con.prepareStatement("SELECT SUM(incomes) FROM companyIncome");
            rs=pst.executeQuery();
            rs.next();
            income=Double.parseDouble(rs.getString(1));
            gincome.setText(Double.toString(income));

            try{
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/double_a","root","97009307");
                pst=con.prepareStatement("SELECT SUM(amount) FROM expense");
                rs=pst.executeQuery();
                rs.next();
                expenses=Double.parseDouble(rs.getString(1));
                Texpense.setText(Double.toString(expenses));
                netProfit.setText(Double.toString(income-expenses));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButtonRecordComputeProfitsActionPerformed

    private void gincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gincomeActionPerformed

    private void agentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentAmountActionPerformed

    private void jButtonRecordCheckAmountCollectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordCheckAmountCollectedActionPerformed
        try{

            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/double_a","root","97009307");
            pst=con.prepareStatement("SELECT SUM(amount) FROM rentStatement WHERE ag_code=?");
            pst.setString(1,agcode.getText());
            rs=pst.executeQuery();
            boolean a=rs.next();
            if(a=false){
             JOptionPane.showMessageDialog(null, "ERROR: Agent Does Not Exist");
                
          }
            
            else{
                agentAmount.setText(rs.getString(1));
            }       
            
            

        }
            
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_jButtonRecordCheckAmountCollectedActionPerformed

    private void agcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agcodeActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        exit.setText("Closes Window");
    }//GEN-LAST:event_jButton1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Texpense;
    private javax.swing.JTextField agcode;
    private javax.swing.JTextField agentAmount;
    private javax.swing.JTable employees;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField gincome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRecordCheckAmountCollected;
    private javax.swing.JButton jButtonRecordComputeProfits;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemMonitorDatabase;
    private javax.swing.JMenuItem jMenuItemRegister;
    private javax.swing.JMenuItem jMenuItemTenantsCollection;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField netProfit;
    private javax.swing.JPanel pane;
    // End of variables declaration//GEN-END:variables
}
