/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package double_a;

import java.sql.*;  
import java.util.*;

import javax.swing.JOptionPane;

        
public class RentReceipt extends javax.swing.JFrame {

    public static final String USERNAME="root";
    public static final String PASSWORD="97009307";
    public static final String CONN ="jdbc:mysql://localhost:3306/double_a";
    
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    int balance;
    
            
    
    public RentReceipt() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        tenant = new javax.swing.JLabel();
        aname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        hsize = new javax.swing.JLabel();
        Hsize = new javax.swing.JComboBox<>();
        hnumber = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        Tenant = new javax.swing.JTextField();
        Aname = new javax.swing.JTextField();
        Hnumber = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButtonGenerateReceipt = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rent Receipt ");

        amount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        amount.setText("Amount Paid");

        tenant.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tenant.setText("Tenant Name");

        aname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        aname.setText("Agent Name");

        lname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lname.setText("Landlord Name");

        hsize.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hsize.setText("House Size");

        Hsize.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Hsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small Size", "Medium Size", "Large Size" }));

        hnumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hnumber.setText("House number");

        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButtonGenerateReceipt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonGenerateReceipt.setText("Generate Receipt");
        jButtonGenerateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateReceiptActionPerformed(evt);
            }
        });

        jButtonPrint.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hsize, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(Hsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Aname, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGenerateReceipt)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrint)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(613, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Aname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hsize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGenerateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPrint)
                            .addComponent(jButtonReset))
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(tenant, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(441, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void jButtonGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {     
        
        Calendar c=Calendar.getInstance();
        int day=c.get(Calendar.DAY_OF_MONTH);
        int month=c.get(Calendar.MONTH);
        int year=c.get(Calendar.YEAR);
        String date=""+day+"-"+month+"-"+year+"";
        try{
            con=DriverManager.getConnection(CONN,USERNAME,PASSWORD); 
            
           
           
           String sele="SELECT balance FROM rentStatement WHERE ag_code='1'";
           
           pst=con.prepareStatement(sele);
           rs=pst.executeQuery();
           while(rs.next()){
               
                balance=Integer.parseInt(rs.getString("balance"));
                balance=balance-Integer.parseInt(Amount.getText());
                JOptionPane.showMessageDialog(null,Tenant.getText());
               
           }
           
           String insert ="INSERT INTO rentStatement (ag_code, amount, date, balance) VALUES (?,?,?,?)";
           pst=con.prepareStatement(insert);
           pst.setString(1,Tenant.getText());
           pst.setString(2, Amount.getText());
           pst.setString(3,date );
           pst.setInt(4,balance);
           
           
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
            
        }
        
       
        area.setText("***************************************************\n");
        area.setText(area.getText()+"                      Rent   Receipt\n");
        area.setText(area.getText()+"***************************************************\n\n");
        area.setText(area.getText()+"                                   "+day+"-"+month+"-"+year+"\n");
        area.setText(area.getText()+tenant.getText()+ " :    "+Tenant.getText()+"\n\n");
        area.setText(area.getText()+amount.getText()+ ":    "+Amount.getText()+".00"+ "\n\n");
        area.setText(area.getText()+hnumber.getText()+ ":    "+Hnumber.getText()+"\n\n");
        area.setText(area.getText()+aname.getText()+ ":    "+Aname.getText()+"\n\n");
        area.setText(area.getText()+lname.getText()+ ":    "+Lname.getText()+"\n\n");
        area.setText(area.getText()+hsize.getText()+ ":    "+Hsize.getSelectedItem()+"\n\n");
        area.setText(area.getText()+"                  BALANCE: "+balance+"\n\n");
        area.setText(area.getText()+"Signature.......................");
    }                                                      

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try{
            area.print();
        }catch(Exception e){
            System.err.print(e);
        }
// TODO add your handling code here:
    }                                            

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        Tenant.setText(null);
        Amount.setText(null);
        Hnumber.setText(null);
        Aname.setText(null);
        Lname.setText(null);
        area.setText(null);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentReceipt().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField Aname;
    private javax.swing.JTextField Hnumber;
    private javax.swing.JComboBox<String> Hsize;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Tenant;
    private javax.swing.JLabel amount;
    private javax.swing.JLabel aname;
    private javax.swing.JTextArea area;
    private javax.swing.JLabel hnumber;
    private javax.swing.JLabel hsize;
    private javax.swing.JButton jButtonGenerateReceipt;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel tenant;
    // End of variables declaration     


    
}


